spring:
  application:
    name: tournament
  datasource:
    url: jdbc:postgresql://localhost:5432/striker_auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
  servlet:
    context-path: /stiker-auth
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: ERROR
  file:
    name: logs/gamestriker.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: logs/gamestriker-%d{yyyy-MM-dd}.%i.log.gz
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 1GB
  loggers:
    com.example.gamestriker: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
        step: 1m

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect