server:
  port: 8080
spring:
  context-path: /api
  datasource:
    url: jdbc:postgresql://localhost:5432/striker_auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
logging:
  level:
    root: INFO
    com.example: DEBUG
  file:
    name: logs/app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: logs/app-%d{yyyy-MM-dd}.%i.log.gz
      max-history: 30
      total-size-cap: 1GB
    triggeringpolicy:
      max-file-size: 10MB

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect